fix the file and identation

diff --git a/.github/workflows/01-BuildingBlock.yaml b/.github/workflows/01-BuildingBlock.yaml
--- a/.github/workflows/01-BuildingBlock.yaml
+++ b/.github/workflows/01-BuildingBlock.yaml
@@ -8,17 +8,17 @@ jobs:
   echo-hello:
     runs-on: ubuntu-latest
     steps:
-    - name: Say hello
-      run: echo "Hello, world!"
+        - name: Say hello
+          run: echo "Hello, world!"
   echo-goodbye:
       runs-on: ubuntu-latest
       steps:
-      - name: Failed Step hello
-        run: 
-          echo "Hello, world!"
-          exit 1
-      - name: Say goodbye
-        run:  echo "Goodbye, world!"
+        - name: Failed Step 
+          run: 
+            echo "I will Fail"
+            exit 1
+        - name: Say goodbye
+          run:  echo "Goodbye, world!"
                
 
     
